stages:
  - build
  - deploy

build:
  stage: build
  image: node:19
  script:
    - echo "Building the project"
    - npm ci
    - npm run build
  only:
    - main

deploy:
  stage: deploy
  image: node:19
  script:
    - echo "Deploying to Vercel"
    # ? Which scope do you want to deploy to? 
    - echo "y\n" | npx vercel --token $VERCEL_TOKEN
  only:
    - main
    - merge_requests
  environment:
    name: production
  variables:
    VERCEL_TOKEN: $VERCEL_TOKEN
