stages:
  - build
  - deploy

build:
  stage: build
  image: node:14
  script:
    - echo "Building the project"
    - npm ci
    - npm run build
  only:
    - merge_requests

deploy:
  stage: deploy
  image: node:14
  script:
    - echo "Deploying to Vercel"
    - npx vercel login --token $VERCEL_TOKEN
    - npx vercel 
  only:
    - master
  environment:
    name: production
  variables:
    VERCEL_TOKEN: $VERCEL_TOKEN
